server:
  servlet:
    context-path: /api
  port: ${SERVER_PORT:3000}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false
  forward-headers-strategy: framework

spring:
  application:
    name: extension-project-api

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:extension-project-api}
    username: ${DB_USER:root}
    password: ${DB_PASS:verysecret}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        time_zone: UTC

jwt:
  secret: 3dMkKj1nbzVj2OY5DJ6T4Qm8Y5ZXx7qA3FV7Xo0Ns38=
